# Travis CI script

language: c

dist: bionic

cache: ccache

matrix:
  include:
  - name: Linux ARM64
    env: BUILD_TYPE=default CURVE=tweetnacl GSSAPI=enabled PGM=enabled NORM=enabled IPv6=ON TLS=enabled DRAFT=enabled
    os: linux
    dist: focal
    arch: arm64
    addons:
      apt:
        packages:
          - zip
          - libkrb5-dev
          - libnorm-dev
          - libpgm-dev
          - libgnutls28-dev

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh

allow_failures:
   - name: Linux ARM64
     env: BUILD_TYPE=default CURVE=tweetnacl GSSAPI=enabled PGM=enabled NORM=enabled IPv6=ON TLS=enabled DRAFT=enabled
     os: linux
     dist: focal
     arch: arm64
